### ISSUE TITLE
Generic Frontend Requests

### ISSUE THREAD

**Issue by rmcilwain6** [Team-Gen/TourneyGen#180]
Just wanted somewhere to document my current wish list of frontend features for Shaelyn! 

- Sidebar should fit to bottom of screen
- Overflow of sidebar should be scrollable, we want the entire screen to be static essentially, the main body should never scroll. 
- I'd like the sidebar to line up with the first navbar component (tournaments) not sure what the best way to go about this is.

**Comment by rmcilwain6** [comment]
More stuff: 
- Sign-in and Sign-up pages have some extra space at the top of the page that needs to be deleted
- Need to add an organization field into the Sign-in page

**Comment by tolkamps1** [comment]
These should all be done except for the organization field which needs further discussion.
